/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
class Library {
  def someLibraryMethod(): Boolean = true

  def main(args: Array[String]): Unit = {
    println("Hello, World!")
  }

  def countChange(money: Int, coins: List[Int]): Int =
    if (money == 0) 1
    else if (coins.isEmpty || money < 0) 0
    else countChange(money - coins.head, coins) + countChange(money, coins.tail)


}
